namespace: development

resources:
- ../../../base


patches:
- target:
    kind: Namespace
    name: default
  patch: |-
    - op: replace
      path: /metadata/name
      value: development
- target:
    kind: Role
    name: pod-reader
  patch: |-
    - op: replace
      path: /metadata
      value: 
        name: dev_reader
        namespace: development
    - op: replace
      path: /rules/0
      value:  
        apiGroups: ["*"] # "" indicates the core API group
        resources: ["*"]
        verbs: ["get", "watch", "list"]
- target:
    kind: RoleBinding
    name: read-pods
  patch: |-
    - op: replace
      path: /metadata
      value:
        name: dev_readers
        namespace: development
    - op: replace
      path: /subjects/0
      value:
        kind: Group
        name: rbac-poc-group@niranjankltest.joonix.net
        apiGroup: rbac.authorization.k8s.io
        namespace: development
    - op: replace
      path: /roleRef
      value:
        kind: Role 
        name: dev_reader  
        apiGroup: rbac.authorization.k8s.io

